# Generated by Django 5.2.3 on 2025-06-13 15:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('house_id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100, unique=True)),
                ('build_year', models.PositiveSmallIntegerField(null=True)),
                ('developer', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(default='2025-06-13T15:08:31')),
                ('update_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(default='2025-06-13T15:08:31')),
                ('role', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Flats',
            fields=[
                ('flat_id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('flat_number', models.PositiveSmallIntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rooms', models.PositiveSmallIntegerField()),
                ('status', models.CharField()),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_house', to='house_app.houses', verbose_name='Дом')),
            ],
        ),
    ]
