# Generated by Django 5.2.3 on 2025-06-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flats',
            old_name='house_id',
            new_name='house',
        ),
        migrations.AlterField(
            model_name='houses',
            name='created_at',
            field=models.DateTimeField(default='2025-06-13T15:19:36'),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default='2025-06-13T15:19:36'),
        ),
    ]
