# Generated by Django 5.2.3 on 2025-06-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default='2025-06-18T10:03:57'),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default='2025-06-18T10:03:57'),
        ),
    ]
