# Generated by Django 5.2.3 on 2025-06-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0002_rename_house_id_flats_house_alter_houses_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='created_at',
            field=models.DateTimeField(default='2025-06-17T12:59:50'),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default='2025-06-17T12:59:50'),
        ),
    ]
