# Generated by Django 5.2.3 on 2025-06-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0003_alter_houses_created_at_alter_users_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='created_at',
            field=models.DateTimeField(default='2025-06-17T13:01:58'),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default='2025-06-17T13:01:58'),
        ),
    ]
